config/routes.rb
Rails.application.routes.draw do

  resources :questions
  resources :users

  get '/register' => 'sessions#new'
  post '/register' => 'sessions#create', :as => :create_user

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#login_attempt'
  delete '/logout' => 'sessions#destroy'
  # post '/users/:id' => ""

  root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :commenter_id, :question_id, :body,  {presence: true}

  belongs_to :commenter, class_name: 'User'
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  belongs_to :question

  def selected_answer(selected_answer)
    if self.id == selected_answer.id
      return true
    end
    false
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :commentable_type, :commenter_id, :commentable_id, :body, {presence: true}

  belongs_to :commenter, class_name: 'User'
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :author_id, :body, :title, {presence: true}

  belongs_to :author, class_name: 'User'
  has_many :comments, as: :commentable
  has_many :votes, as: :votable
  has_many :answers

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, foreign_key: :author_id
  has_many :answers, foreign_key: :commenter_id
  has_many :votes, foreign_key: :voter_id
  has_many :comments, foreign_key: :commenter_id
  has_many :answered_questions, through: :answers, source: :question

  validates :username,  :password_digest, {presence: true}
  validates :email, {uniqueness: true}

  has_secure_password
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :votable_id, :votable_type, :voter_id, {presence: true}
  validates :voter_id, uniqueness: {scope: [:votable_id, :votable_type, :vote_direction]}

  belongs_to :voter, class_name: 'User'
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  def current_user
    @_current_user ||= session[:user_id] &&
      User.find_by(id: session[:user_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render 'users/new'
  end

  def create
    @user = User.create!(user_params)
    redirect_to user_path(@user)
  end

  def login_attempt
    user = User.find_by(username: params[:username])
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_url
    end
  end

  def destroy
    @_current_user = session[:current_user_id] = nil
    redirect_to root_url
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.create!(user_params)
  #   redirect_to user_path(@user)
  # end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflowJr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_question.html.erb
<li><%= link_to question.title, question_path(question) %><br>
  <%= question.body %>
</li><br><br>

app/views/questions/index.html.erb
<%= link_to 'Login', login_path %><br><br>

<%= link_to 'Register', register_path %><br><br>

<%= link_to 'New Question', new_question_path %>
<br><br>
<%= render @questions %>

app/views/questions/new.html.erb
<%= form_for(@question) do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body %>
  <%= f.text_field :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/questions/show.html.erb
<p><%= @question.title %></p>
<p><%= @question.body %></p>

app/views/users/new.html.erb
<%= form_for @user, url: create_user_path do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<%= @user.username %>
<%= @user.email %>

<% @user.questions.each do |question| %>
  <ul>
    <li><%= link_to question.title, question_path %>    </li>
  </ul>
<% end %>